### PR TITLE
Update ShortGuid.cs

### PR DESCRIPTION
**Pull request by vanillajonathan**
Explicitly declare property visibility.
Proper capitalization of Base64.
Proper punctuation.

### CODE REVIEW

**Comment by vanillajonathan** [comment]
@davetransom ping!

**Comment by davetransom** [comment]
Sorry @vanillajonathan, I forgot about this one when I didn't quite know how I should reply straight away.

The documentation corrections are worth accepting (and thank you), however, reorganising the struct is not something I'd merge as I've written it the way I want it.

I'll happily merge if you revert the stylistic changes.

**Comment by vanillajonathan** [comment]
But members of a class should be have theit member visibility explicitly declared<s>, and if not explicitly declared as private, they are implicitly internal, and in this case I believe they should be private</s>. Also private and internal members should be placed above public members, and non-static members should be placed above static members according to the [Microsoft Framework Design Guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/).

**Comment by davetransom** [comment]
Are you confusing default access modifiers for class (internal) vs members (private)?

My previous comment still stands.

**Comment by vanillajonathan** [comment]
Yes. I am confusing default ass modifiers.

I updated the patch.

**Comment by vanillajonathan** [comment]
Yes. I am confusing default access modifiers.

I updated the patch.

**Pull request merged**
